---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: executions.closedlooppooc.closedloop.io
spec:
  group: closedlooppooc.closedloop.io
  names:
    kind: Execution
    listKind: ExecutionList
    plural: executions
    singular: execution
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Execution is the Schema for the executions API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ExecutionSpec defines the desired state of Execution
            properties:
              action:
                type: string
              affix:
                description: 'Important: Run "make" to regenerate code after modifying
                  this file This is where you define what Spec you want for your CR
                  Decision'
                type: string
              executiontypeid:
                format: int32
                type: integer
              time:
                type: string
            required:
            - action
            - executiontypeid
            type: object
          status:
            description: ExecutionStatus defines the observed state of Execution
            properties:
              affix:
                description: 'Important: Run "make" to regenerate code after modifying
                  this file'
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
